locals {
  firewall_name = "${var.host_name}-firewall"
  server_name = "${var.host_name}"
  ssh_key_name = "${var.host_name}-ssh-key"
  volume_name = "${var.host_name}-volume"
}

resource "hcloud_firewall" "firewall" {
  name = local.firewall_name
  
  rule {
    direction  = "in"
    port       = "22"
    protocol   = "tcp"
    source_ips = ["0.0.0.0/0", "::/0"]
  }
  
  dynamic "rule" {
    for_each = var.additional_firewall_rules
    content {
      direction  = rule.value.direction
      port       = rule.value.port
      protocol   = rule.value.protocol
      source_ips = rule.value.source_ips
    }
  }
}

resource "hcloud_ssh_key" "ssh_public_key" {
  name       = local.ssh_key_name
  public_key = file(var.ssh_public_key_path)
}

resource "hcloud_volume" "volume" {
  count    = var.volume_size != null ? 1 : 0
  name     = local.volume_name
  size     = var.volume_size
  location = var.location
  format   = "xfs"
}

resource "hcloud_volume_attachment" "volume_attachment" {
  count     = var.volume_size != null ? 1 : 0
  volume_id = hcloud_volume.volume[0].id
  server_id = hcloud_server.server.id
  automount = true
}

resource "hcloud_server" "server" {
  name               = local.server_name
  image              = "ubuntu-22.04"
  server_type        = var.server_type
  location           = var.location
  ssh_keys           = [hcloud_ssh_key.ssh_public_key.id]
  backups            = var.enable_backups
  delete_protection  = var.enable_delete_protection
  firewall_ids       = [hcloud_firewall.firewall.id]

  labels = var.labels
  
  user_data = md5(join("", [for f in fileset("${path.module}/nix", "**/*.nix") : f != "configuration.nix" ? filemd5("${path.module}/nix/${f}") : ""]))  
}

resource "local_file" "nixos_configuration" {
  
  content = templatefile("${path.module}/nix/configuration.nix.tpl", {
    hostname           = var.host_name
    ssh_public_key     = trimspace(file(var.ssh_public_key_path))
    volume_size        = var.volume_size
    volume_mount_point = var.volume_mount_point
  })
  filename = "${path.module}/nix/configuration.nix"
}

resource "null_resource" "nixos_deployment" {
  depends_on = [hcloud_server.server, local_file.nixos_configuration]
  
  triggers = {
    server_id = hcloud_server.server.id
  }
  
  provisioner "local-exec" {
    command = <<-EOF
      set -e  # Exit on any error
      
      # Wait for server to be ready
      sleep 30
      
      # Remove old host key
      ssh-keygen -R ${hcloud_server.server.ipv4_address} || true

      # Setup SSH key arguments if private key is provided
      SSH_KEY_ARGS=""
      if [[ -n "${var.ssh_private_key_path}" ]]; then
        SSH_KEY_ARGS="-i ${var.ssh_private_key_path}"
      fi

      # Detect main disk and update disko config
      MAIN_DISK=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_KEY_ARGS root@${hcloud_server.server.ipv4_address} \
        "find /dev/disk/by-id/ -name 'scsi-0QEMU_QEMU_HARDDISK*' | grep -v 'part[0-9]' | head -1")
      
      echo "Detected main disk: $MAIN_DISK"
      
      # Fallback to /dev/sda if detection fails
      if [ -z "$MAIN_DISK" ]; then
        echo "No QEMU disk found, using /dev/sda as fallback"
        MAIN_DISK="/dev/sda"
      fi
      
      # Update disko config with detected disk
      sed -i "s|device = \"\";|device = \"$MAIN_DISK\";|" \
        ${path.module}/nix/disko.nix
      
      # Configuration.nix is already generated by terraform local_file resource
      
      # Deploy NixOS with flake using private key if provided
      NIXOS_ANYWHERE_ARGS=""
      if [[ -n "${var.ssh_private_key_path}" ]]; then
        NIXOS_ANYWHERE_ARGS="-i ${var.ssh_private_key_path}"
      fi
      
      # Use path: prefix to include untracked files like the generated configuration.nix
      # which is created by terraform template and not versioned in git
      if ! nix run github:nix-community/nixos-anywhere -- $NIXOS_ANYWHERE_ARGS --flake path:${path.module}/nix#default root@${hcloud_server.server.ipv4_address} ; then
        echo "ERROR: nixos-anywhere deployment failed!"
        exit 1
      fi
      
      echo "SUCCESS: NixOS deployment completed"
    EOF
    
    working_dir = path.cwd
  }
}
